# Generated by Django 2.1.7 on 2019-04-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.CharField(max_length=3, verbose_name='年龄')),
                ('telephone', models.CharField(max_length=32, verbose_name='手机号')),
                ('classes', models.IntegerField(choices=[(1, '九年级一班'), (2, '九年级二班'), (3, '九年级三班')], default=1, verbose_name='班级')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Department', verbose_name='部门')),
                ('roles', models.ManyToManyField(blank=True, null=True, to='rbac.Role', verbose_name='拥有的所有角色')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
