# Generated by Django 2.1.7 on 2019-04-22 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_classlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_teacher',
            field=models.ForeignKey(limit_choices_to={'depart__title': '教质部'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='web.UserInfo', verbose_name='班主任'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Course', verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='graduate_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结业日期'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='tech_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'depart__title__in': ['Linux教学部', 'Python教学部']}, null=True, related_name='teach_classes', to='web.UserInfo', verbose_name='任课老师'),
        ),
    ]
